
## Here include some basic information
## Name of author:Robert Wynne
## Date:24/01/2020
## Program name: .Rmd
## Purpose of the script: plot euler
## This script does XX, YYY and ZZZ.
##
## Mention what it takes as input
##
## It outputs... - We can work on this when I get back.

First step, load library required for plotting:

```{r, message = FALSE}
##install.packages("eulerr")
library(eulerr)
library(ggplot2)
```

Next, load input data:

```{r, message = FALSE}
load(file = "../data/DESeq2_output_liver.RData")
```

Create a list of comparisons to plot:

```{r, message = FALSE}
vendiagram <- euler(combinations = list("Smolt vs Non Smolt saltwater" = smolt_vs_non_smolts_salt_lrt_wald,
                                        "Non Smolt saltwater vs Non Smolt freshwater" = smolt_vs_non_smolts_fresh_lrt_wald,
                                        "Smolt vs Non Smolt freshwater" = non_smolt_salt_vs_non_smolts_fresh_lrt_wald))
```

Plot Venn diagram

```{r, message = FALSE}
plot(vendiagram,
     quantities = TRUE,
     edges = TRUE)

## Save image to file:
dir.create(path = "./euler_plots")
ggsave(filename = "./euler_plots/comparison_degs.png",
       width = 5,
       height = 5)
```

